name: model_mapper
description: Intelligent object mapping for Dart.
version: 0.1.2
homepage: https://github.com/T-Oner/model_mapper

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.0

dev_dependencies:
  test: ^1.16.8
  build_runner: ^1.10.3
  json_serializable: ^4.0.0
  model_mapper_generator: ^0.1.2